/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.keymanager.provider.db.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.keymanager.provider.db.model.KeyEntry;
import com.liferay.keymanager.provider.db.model.KeyEntryModel;
import com.liferay.keymanager.provider.db.model.KeyEntryWrappedKeyBlobBlobModel;
import com.liferay.keymanager.provider.db.service.KeyEntryLocalServiceUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KeyEntry service. Represents a row in the &quot;KeyManagerDB_KeyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KeyEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KeyEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeyEntryImpl
 * @generated
 */
public class KeyEntryModelImpl
	extends BaseModelImpl<KeyEntry> implements KeyEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a key entry model instance should use the <code>KeyEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "KeyManagerDB_KeyEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"keyEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"alias_", Types.VARCHAR},
		{"keyType", Types.VARCHAR}, {"algorithm", Types.VARCHAR},
		{"cipherSpec", Types.VARCHAR}, {"wrappedKeyBlob", Types.BLOB},
		{"kekReference", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("keyEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("alias_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("keyType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("algorithm", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cipherSpec", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("wrappedKeyBlob", Types.BLOB);
		TABLE_COLUMNS_MAP.put("kekReference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table KeyManagerDB_KeyEntry (mvccVersion LONG default 0 not null,keyEntryId LONG not null primary key,companyId LONG,alias_ VARCHAR(75) null,keyType VARCHAR(75) null,algorithm VARCHAR(75) null,cipherSpec VARCHAR(75) null,wrappedKeyBlob BLOB,kekReference VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table KeyManagerDB_KeyEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY keyEntry.keyEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY KeyManagerDB_KeyEntry.keyEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ALIAS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KEYENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public KeyEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _keyEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKeyEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _keyEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KeyEntry.class;
	}

	@Override
	public String getModelClassName() {
		return KeyEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KeyEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KeyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KeyEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((KeyEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KeyEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KeyEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KeyEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KeyEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KeyEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<KeyEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<KeyEntry, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<KeyEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", KeyEntry::getMvccVersion);
			attributeGetterFunctions.put("keyEntryId", KeyEntry::getKeyEntryId);
			attributeGetterFunctions.put("companyId", KeyEntry::getCompanyId);
			attributeGetterFunctions.put("alias", KeyEntry::getAlias);
			attributeGetterFunctions.put("keyType", KeyEntry::getKeyType);
			attributeGetterFunctions.put("algorithm", KeyEntry::getAlgorithm);
			attributeGetterFunctions.put("cipherSpec", KeyEntry::getCipherSpec);
			attributeGetterFunctions.put(
				"wrappedKeyBlob", KeyEntry::getWrappedKeyBlob);
			attributeGetterFunctions.put(
				"kekReference", KeyEntry::getKekReference);
			attributeGetterFunctions.put("createDate", KeyEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", KeyEntry::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<KeyEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<KeyEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<KeyEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<KeyEntry, Long>)KeyEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"keyEntryId",
				(BiConsumer<KeyEntry, Long>)KeyEntry::setKeyEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<KeyEntry, Long>)KeyEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"alias", (BiConsumer<KeyEntry, String>)KeyEntry::setAlias);
			attributeSetterBiConsumers.put(
				"keyType", (BiConsumer<KeyEntry, String>)KeyEntry::setKeyType);
			attributeSetterBiConsumers.put(
				"algorithm",
				(BiConsumer<KeyEntry, String>)KeyEntry::setAlgorithm);
			attributeSetterBiConsumers.put(
				"cipherSpec",
				(BiConsumer<KeyEntry, String>)KeyEntry::setCipherSpec);
			attributeSetterBiConsumers.put(
				"wrappedKeyBlob",
				(BiConsumer<KeyEntry, Blob>)KeyEntry::setWrappedKeyBlob);
			attributeSetterBiConsumers.put(
				"kekReference",
				(BiConsumer<KeyEntry, String>)KeyEntry::setKekReference);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<KeyEntry, Date>)KeyEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<KeyEntry, Date>)KeyEntry::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getKeyEntryId() {
		return _keyEntryId;
	}

	@Override
	public void setKeyEntryId(long keyEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_keyEntryId = keyEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getAlias() {
		if (_alias == null) {
			return "";
		}
		else {
			return _alias;
		}
	}

	@Override
	public void setAlias(String alias) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_alias = alias;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAlias() {
		return getColumnOriginalValue("alias_");
	}

	@Override
	public String getKeyType() {
		if (_keyType == null) {
			return "";
		}
		else {
			return _keyType;
		}
	}

	@Override
	public void setKeyType(String keyType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_keyType = keyType;
	}

	@Override
	public String getAlgorithm() {
		if (_algorithm == null) {
			return "";
		}
		else {
			return _algorithm;
		}
	}

	@Override
	public void setAlgorithm(String algorithm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_algorithm = algorithm;
	}

	@Override
	public String getCipherSpec() {
		if (_cipherSpec == null) {
			return "";
		}
		else {
			return _cipherSpec;
		}
	}

	@Override
	public void setCipherSpec(String cipherSpec) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cipherSpec = cipherSpec;
	}

	@Override
	public Blob getWrappedKeyBlob() {
		if (_wrappedKeyBlobBlobModel == null) {
			try {
				_wrappedKeyBlobBlobModel =
					KeyEntryLocalServiceUtil.getWrappedKeyBlobBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_wrappedKeyBlobBlobModel != null) {
			blob = _wrappedKeyBlobBlobModel.getWrappedKeyBlobBlob();
		}

		return blob;
	}

	@Override
	public void setWrappedKeyBlob(Blob wrappedKeyBlob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_wrappedKeyBlobBlobModel == null) {
			_wrappedKeyBlobBlobModel = new KeyEntryWrappedKeyBlobBlobModel(
				getPrimaryKey(), wrappedKeyBlob);
		}
		else {
			_wrappedKeyBlobBlobModel.setWrappedKeyBlobBlob(wrappedKeyBlob);
		}
	}

	@Override
	public String getKekReference() {
		if (_kekReference == null) {
			return "";
		}
		else {
			return _kekReference;
		}
	}

	@Override
	public void setKekReference(String kekReference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kekReference = kekReference;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), KeyEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KeyEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KeyEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KeyEntryImpl keyEntryImpl = new KeyEntryImpl();

		keyEntryImpl.setMvccVersion(getMvccVersion());
		keyEntryImpl.setKeyEntryId(getKeyEntryId());
		keyEntryImpl.setCompanyId(getCompanyId());
		keyEntryImpl.setAlias(getAlias());
		keyEntryImpl.setKeyType(getKeyType());
		keyEntryImpl.setAlgorithm(getAlgorithm());
		keyEntryImpl.setCipherSpec(getCipherSpec());
		keyEntryImpl.setKekReference(getKekReference());
		keyEntryImpl.setCreateDate(getCreateDate());
		keyEntryImpl.setModifiedDate(getModifiedDate());

		keyEntryImpl.resetOriginalValues();

		return keyEntryImpl;
	}

	@Override
	public KeyEntry cloneWithOriginalValues() {
		KeyEntryImpl keyEntryImpl = new KeyEntryImpl();

		keyEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		keyEntryImpl.setKeyEntryId(
			this.<Long>getColumnOriginalValue("keyEntryId"));
		keyEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		keyEntryImpl.setAlias(this.<String>getColumnOriginalValue("alias_"));
		keyEntryImpl.setKeyType(this.<String>getColumnOriginalValue("keyType"));
		keyEntryImpl.setAlgorithm(
			this.<String>getColumnOriginalValue("algorithm"));
		keyEntryImpl.setCipherSpec(
			this.<String>getColumnOriginalValue("cipherSpec"));
		keyEntryImpl.setKekReference(
			this.<String>getColumnOriginalValue("kekReference"));
		keyEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		keyEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return keyEntryImpl;
	}

	@Override
	public int compareTo(KeyEntry keyEntry) {
		long primaryKey = keyEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KeyEntry)) {
			return false;
		}

		KeyEntry keyEntry = (KeyEntry)object;

		long primaryKey = keyEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_wrappedKeyBlobBlobModel = null;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KeyEntry> toCacheModel() {
		KeyEntryCacheModel keyEntryCacheModel = new KeyEntryCacheModel();

		keyEntryCacheModel.mvccVersion = getMvccVersion();

		keyEntryCacheModel.keyEntryId = getKeyEntryId();

		keyEntryCacheModel.companyId = getCompanyId();

		keyEntryCacheModel.alias = getAlias();

		String alias = keyEntryCacheModel.alias;

		if ((alias != null) && (alias.length() == 0)) {
			keyEntryCacheModel.alias = null;
		}

		keyEntryCacheModel.keyType = getKeyType();

		String keyType = keyEntryCacheModel.keyType;

		if ((keyType != null) && (keyType.length() == 0)) {
			keyEntryCacheModel.keyType = null;
		}

		keyEntryCacheModel.algorithm = getAlgorithm();

		String algorithm = keyEntryCacheModel.algorithm;

		if ((algorithm != null) && (algorithm.length() == 0)) {
			keyEntryCacheModel.algorithm = null;
		}

		keyEntryCacheModel.cipherSpec = getCipherSpec();

		String cipherSpec = keyEntryCacheModel.cipherSpec;

		if ((cipherSpec != null) && (cipherSpec.length() == 0)) {
			keyEntryCacheModel.cipherSpec = null;
		}

		keyEntryCacheModel.kekReference = getKekReference();

		String kekReference = keyEntryCacheModel.kekReference;

		if ((kekReference != null) && (kekReference.length() == 0)) {
			keyEntryCacheModel.kekReference = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			keyEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			keyEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			keyEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			keyEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return keyEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{\"mvccVersion\": ");

		sb.append(getMvccVersion());

		sb.append(", \"keyEntryId\": ");

		sb.append(getKeyEntryId());

		sb.append(", \"companyId\": ");

		sb.append(getCompanyId());

		sb.append(", \"alias\": ");

		sb.append("\"" + getAlias() + "\"");

		sb.append(", \"keyType\": ");

		sb.append("\"" + getKeyType() + "\"");

		sb.append(", \"algorithm\": ");

		sb.append("\"" + getAlgorithm() + "\"");

		sb.append(", \"cipherSpec\": ");

		sb.append("\"" + getCipherSpec() + "\"");

		sb.append(", \"kekReference\": ");

		sb.append("\"" + getKekReference() + "\"");

		sb.append(", \"createDate\": ");

		sb.append("\"" + getCreateDate() + "\"");

		sb.append(", \"modifiedDate\": ");

		sb.append("\"" + getModifiedDate() + "\"");

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KeyEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					KeyEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _keyEntryId;
	private long _companyId;
	private String _alias;
	private String _keyType;
	private String _algorithm;
	private String _cipherSpec;
	private transient KeyEntryWrappedKeyBlobBlobModel _wrappedKeyBlobBlobModel;
	private String _kekReference;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<KeyEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((KeyEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("keyEntryId", _keyEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("alias_", _alias);
		_columnOriginalValues.put("keyType", _keyType);
		_columnOriginalValues.put("algorithm", _algorithm);
		_columnOriginalValues.put("cipherSpec", _cipherSpec);
		_columnOriginalValues.put("kekReference", _kekReference);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("alias_", "alias");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("keyEntryId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("alias_", 8L);

		columnBitmasks.put("keyType", 16L);

		columnBitmasks.put("algorithm", 32L);

		columnBitmasks.put("cipherSpec", 64L);

		columnBitmasks.put("wrappedKeyBlob", 128L);

		columnBitmasks.put("kekReference", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private KeyEntry _escapedModel;

}