/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.keymanager.provider.db.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.keymanager.provider.db.model.SecretEntry;
import com.liferay.keymanager.provider.db.model.SecretEntryCiphertextBlobBlobModel;
import com.liferay.keymanager.provider.db.model.SecretEntryEncryptedDEKBlobBlobModel;
import com.liferay.keymanager.provider.db.model.SecretEntryModel;
import com.liferay.keymanager.provider.db.service.SecretEntryLocalServiceUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SecretEntry service. Represents a row in the &quot;KeyManagerDB_SecretEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SecretEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecretEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecretEntryImpl
 * @generated
 */
public class SecretEntryModelImpl
	extends BaseModelImpl<SecretEntry> implements SecretEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a secret entry model instance should use the <code>SecretEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "KeyManagerDB_SecretEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"secretEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"alias_", Types.VARCHAR},
		{"ciphertextBlob", Types.BLOB}, {"iv", Types.VARCHAR},
		{"encryptedDEKBlob", Types.BLOB}, {"dekIv", Types.VARCHAR},
		{"kekReference", Types.VARCHAR}, {"algorithm", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("secretEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("alias_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ciphertextBlob", Types.BLOB);
		TABLE_COLUMNS_MAP.put("iv", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("encryptedDEKBlob", Types.BLOB);
		TABLE_COLUMNS_MAP.put("dekIv", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kekReference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("algorithm", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table KeyManagerDB_SecretEntry (mvccVersion LONG default 0 not null,secretEntryId LONG not null primary key,companyId LONG,alias_ VARCHAR(75) null,ciphertextBlob BLOB,iv VARCHAR(75) null,encryptedDEKBlob BLOB,dekIv VARCHAR(75) null,kekReference VARCHAR(75) null,algorithm VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table KeyManagerDB_SecretEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY secretEntry.secretEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY KeyManagerDB_SecretEntry.secretEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ALIAS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SECRETENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SecretEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _secretEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSecretEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _secretEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SecretEntry.class;
	}

	@Override
	public String getModelClassName() {
		return SecretEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SecretEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SecretEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecretEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SecretEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SecretEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SecretEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SecretEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SecretEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SecretEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SecretEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SecretEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<SecretEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", SecretEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"secretEntryId", SecretEntry::getSecretEntryId);
			attributeGetterFunctions.put(
				"companyId", SecretEntry::getCompanyId);
			attributeGetterFunctions.put("alias", SecretEntry::getAlias);
			attributeGetterFunctions.put(
				"ciphertextBlob", SecretEntry::getCiphertextBlob);
			attributeGetterFunctions.put("iv", SecretEntry::getIv);
			attributeGetterFunctions.put(
				"encryptedDEKBlob", SecretEntry::getEncryptedDEKBlob);
			attributeGetterFunctions.put("dekIv", SecretEntry::getDekIv);
			attributeGetterFunctions.put(
				"kekReference", SecretEntry::getKekReference);
			attributeGetterFunctions.put(
				"algorithm", SecretEntry::getAlgorithm);
			attributeGetterFunctions.put(
				"createDate", SecretEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", SecretEntry::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SecretEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SecretEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SecretEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<SecretEntry, Long>)SecretEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"secretEntryId",
				(BiConsumer<SecretEntry, Long>)SecretEntry::setSecretEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SecretEntry, Long>)SecretEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"alias",
				(BiConsumer<SecretEntry, String>)SecretEntry::setAlias);
			attributeSetterBiConsumers.put(
				"ciphertextBlob",
				(BiConsumer<SecretEntry, Blob>)SecretEntry::setCiphertextBlob);
			attributeSetterBiConsumers.put(
				"iv", (BiConsumer<SecretEntry, String>)SecretEntry::setIv);
			attributeSetterBiConsumers.put(
				"encryptedDEKBlob",
				(BiConsumer<SecretEntry, Blob>)
					SecretEntry::setEncryptedDEKBlob);
			attributeSetterBiConsumers.put(
				"dekIv",
				(BiConsumer<SecretEntry, String>)SecretEntry::setDekIv);
			attributeSetterBiConsumers.put(
				"kekReference",
				(BiConsumer<SecretEntry, String>)SecretEntry::setKekReference);
			attributeSetterBiConsumers.put(
				"algorithm",
				(BiConsumer<SecretEntry, String>)SecretEntry::setAlgorithm);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SecretEntry, Date>)SecretEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SecretEntry, Date>)SecretEntry::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getSecretEntryId() {
		return _secretEntryId;
	}

	@Override
	public void setSecretEntryId(long secretEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secretEntryId = secretEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getAlias() {
		if (_alias == null) {
			return "";
		}
		else {
			return _alias;
		}
	}

	@Override
	public void setAlias(String alias) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_alias = alias;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAlias() {
		return getColumnOriginalValue("alias_");
	}

	@Override
	public Blob getCiphertextBlob() {
		if (_ciphertextBlobBlobModel == null) {
			try {
				_ciphertextBlobBlobModel =
					SecretEntryLocalServiceUtil.getCiphertextBlobBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_ciphertextBlobBlobModel != null) {
			blob = _ciphertextBlobBlobModel.getCiphertextBlobBlob();
		}

		return blob;
	}

	@Override
	public void setCiphertextBlob(Blob ciphertextBlob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_ciphertextBlobBlobModel == null) {
			_ciphertextBlobBlobModel = new SecretEntryCiphertextBlobBlobModel(
				getPrimaryKey(), ciphertextBlob);
		}
		else {
			_ciphertextBlobBlobModel.setCiphertextBlobBlob(ciphertextBlob);
		}
	}

	@Override
	public String getIv() {
		if (_iv == null) {
			return "";
		}
		else {
			return _iv;
		}
	}

	@Override
	public void setIv(String iv) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iv = iv;
	}

	@Override
	public Blob getEncryptedDEKBlob() {
		if (_encryptedDEKBlobBlobModel == null) {
			try {
				_encryptedDEKBlobBlobModel =
					SecretEntryLocalServiceUtil.getEncryptedDEKBlobBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_encryptedDEKBlobBlobModel != null) {
			blob = _encryptedDEKBlobBlobModel.getEncryptedDEKBlobBlob();
		}

		return blob;
	}

	@Override
	public void setEncryptedDEKBlob(Blob encryptedDEKBlob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_encryptedDEKBlobBlobModel == null) {
			_encryptedDEKBlobBlobModel =
				new SecretEntryEncryptedDEKBlobBlobModel(
					getPrimaryKey(), encryptedDEKBlob);
		}
		else {
			_encryptedDEKBlobBlobModel.setEncryptedDEKBlobBlob(
				encryptedDEKBlob);
		}
	}

	@Override
	public String getDekIv() {
		if (_dekIv == null) {
			return "";
		}
		else {
			return _dekIv;
		}
	}

	@Override
	public void setDekIv(String dekIv) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dekIv = dekIv;
	}

	@Override
	public String getKekReference() {
		if (_kekReference == null) {
			return "";
		}
		else {
			return _kekReference;
		}
	}

	@Override
	public void setKekReference(String kekReference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kekReference = kekReference;
	}

	@Override
	public String getAlgorithm() {
		if (_algorithm == null) {
			return "";
		}
		else {
			return _algorithm;
		}
	}

	@Override
	public void setAlgorithm(String algorithm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_algorithm = algorithm;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SecretEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SecretEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SecretEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SecretEntryImpl secretEntryImpl = new SecretEntryImpl();

		secretEntryImpl.setMvccVersion(getMvccVersion());
		secretEntryImpl.setSecretEntryId(getSecretEntryId());
		secretEntryImpl.setCompanyId(getCompanyId());
		secretEntryImpl.setAlias(getAlias());
		secretEntryImpl.setIv(getIv());
		secretEntryImpl.setDekIv(getDekIv());
		secretEntryImpl.setKekReference(getKekReference());
		secretEntryImpl.setAlgorithm(getAlgorithm());
		secretEntryImpl.setCreateDate(getCreateDate());
		secretEntryImpl.setModifiedDate(getModifiedDate());

		secretEntryImpl.resetOriginalValues();

		return secretEntryImpl;
	}

	@Override
	public SecretEntry cloneWithOriginalValues() {
		SecretEntryImpl secretEntryImpl = new SecretEntryImpl();

		secretEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		secretEntryImpl.setSecretEntryId(
			this.<Long>getColumnOriginalValue("secretEntryId"));
		secretEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		secretEntryImpl.setAlias(this.<String>getColumnOriginalValue("alias_"));
		secretEntryImpl.setIv(this.<String>getColumnOriginalValue("iv"));
		secretEntryImpl.setDekIv(this.<String>getColumnOriginalValue("dekIv"));
		secretEntryImpl.setKekReference(
			this.<String>getColumnOriginalValue("kekReference"));
		secretEntryImpl.setAlgorithm(
			this.<String>getColumnOriginalValue("algorithm"));
		secretEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		secretEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return secretEntryImpl;
	}

	@Override
	public int compareTo(SecretEntry secretEntry) {
		long primaryKey = secretEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SecretEntry)) {
			return false;
		}

		SecretEntry secretEntry = (SecretEntry)object;

		long primaryKey = secretEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_ciphertextBlobBlobModel = null;

		_encryptedDEKBlobBlobModel = null;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SecretEntry> toCacheModel() {
		SecretEntryCacheModel secretEntryCacheModel =
			new SecretEntryCacheModel();

		secretEntryCacheModel.mvccVersion = getMvccVersion();

		secretEntryCacheModel.secretEntryId = getSecretEntryId();

		secretEntryCacheModel.companyId = getCompanyId();

		secretEntryCacheModel.alias = getAlias();

		String alias = secretEntryCacheModel.alias;

		if ((alias != null) && (alias.length() == 0)) {
			secretEntryCacheModel.alias = null;
		}

		secretEntryCacheModel.iv = getIv();

		String iv = secretEntryCacheModel.iv;

		if ((iv != null) && (iv.length() == 0)) {
			secretEntryCacheModel.iv = null;
		}

		secretEntryCacheModel.dekIv = getDekIv();

		String dekIv = secretEntryCacheModel.dekIv;

		if ((dekIv != null) && (dekIv.length() == 0)) {
			secretEntryCacheModel.dekIv = null;
		}

		secretEntryCacheModel.kekReference = getKekReference();

		String kekReference = secretEntryCacheModel.kekReference;

		if ((kekReference != null) && (kekReference.length() == 0)) {
			secretEntryCacheModel.kekReference = null;
		}

		secretEntryCacheModel.algorithm = getAlgorithm();

		String algorithm = secretEntryCacheModel.algorithm;

		if ((algorithm != null) && (algorithm.length() == 0)) {
			secretEntryCacheModel.algorithm = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			secretEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			secretEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			secretEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			secretEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return secretEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{\"mvccVersion\": ");

		sb.append(getMvccVersion());

		sb.append(", \"secretEntryId\": ");

		sb.append(getSecretEntryId());

		sb.append(", \"companyId\": ");

		sb.append(getCompanyId());

		sb.append(", \"alias\": ");

		sb.append("\"" + getAlias() + "\"");

		sb.append(", \"iv\": ");

		sb.append("\"" + getIv() + "\"");

		sb.append(", \"dekIv\": ");

		sb.append("\"" + getDekIv() + "\"");

		sb.append(", \"kekReference\": ");

		sb.append("\"" + getKekReference() + "\"");

		sb.append(", \"algorithm\": ");

		sb.append("\"" + getAlgorithm() + "\"");

		sb.append(", \"createDate\": ");

		sb.append("\"" + getCreateDate() + "\"");

		sb.append(", \"modifiedDate\": ");

		sb.append("\"" + getModifiedDate() + "\"");

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SecretEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SecretEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _secretEntryId;
	private long _companyId;
	private String _alias;
	private transient SecretEntryCiphertextBlobBlobModel
		_ciphertextBlobBlobModel;
	private String _iv;
	private transient SecretEntryEncryptedDEKBlobBlobModel
		_encryptedDEKBlobBlobModel;
	private String _dekIv;
	private String _kekReference;
	private String _algorithm;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SecretEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SecretEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("secretEntryId", _secretEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("alias_", _alias);
		_columnOriginalValues.put("iv", _iv);
		_columnOriginalValues.put("dekIv", _dekIv);
		_columnOriginalValues.put("kekReference", _kekReference);
		_columnOriginalValues.put("algorithm", _algorithm);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("alias_", "alias");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("secretEntryId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("alias_", 8L);

		columnBitmasks.put("ciphertextBlob", 16L);

		columnBitmasks.put("iv", 32L);

		columnBitmasks.put("encryptedDEKBlob", 64L);

		columnBitmasks.put("dekIv", 128L);

		columnBitmasks.put("kekReference", 256L);

		columnBitmasks.put("algorithm", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SecretEntry _escapedModel;

}