/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.otp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the OTPEmail service. Represents a row in the &quot;OTPEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPEmailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPEmailImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see OTPEmail
 * @see com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPEmailImpl
 * @see com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPEmailModelImpl
 * @generated
 */
@ProviderType
public interface OTPEmailModel extends AuditedModel, BaseModel<OTPEmail>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a otp email model instance should use the {@link OTPEmail} interface instead.
	 */

	/**
	 * Returns the primary key of this otp email.
	 *
	 * @return the primary key of this otp email
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this otp email.
	 *
	 * @param primaryKey the primary key of this otp email
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the otp email ID of this otp email.
	 *
	 * @return the otp email ID of this otp email
	 */
	public long getOtpEmailId();

	/**
	 * Sets the otp email ID of this otp email.
	 *
	 * @param otpEmailId the otp email ID of this otp email
	 */
	public void setOtpEmailId(long otpEmailId);

	/**
	 * Returns the company ID of this otp email.
	 *
	 * @return the company ID of this otp email
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this otp email.
	 *
	 * @param companyId the company ID of this otp email
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this otp email.
	 *
	 * @return the user ID of this otp email
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this otp email.
	 *
	 * @param userId the user ID of this otp email
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this otp email.
	 *
	 * @return the user uuid of this otp email
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this otp email.
	 *
	 * @param userUuid the user uuid of this otp email
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this otp email.
	 *
	 * @return the user name of this otp email
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this otp email.
	 *
	 * @param userName the user name of this otp email
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this otp email.
	 *
	 * @return the create date of this otp email
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this otp email.
	 *
	 * @param createDate the create date of this otp email
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this otp email.
	 *
	 * @return the modified date of this otp email
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this otp email.
	 *
	 * @param modifiedDate the modified date of this otp email
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the backup codes of this otp email.
	 *
	 * @return the backup codes of this otp email
	 */
	@AutoEscape
	public String getBackupCodes();

	/**
	 * Sets the backup codes of this otp email.
	 *
	 * @param backupCodes the backup codes of this otp email
	 */
	public void setBackupCodes(String backupCodes);

	/**
	 * Returns the last login date of this otp email.
	 *
	 * @return the last login date of this otp email
	 */
	public Date getLastLoginDate();

	/**
	 * Sets the last login date of this otp email.
	 *
	 * @param lastLoginDate the last login date of this otp email
	 */
	public void setLastLoginDate(Date lastLoginDate);

	/**
	 * Returns the last login ip of this otp email.
	 *
	 * @return the last login ip of this otp email
	 */
	@AutoEscape
	public String getLastLoginIP();

	/**
	 * Sets the last login ip of this otp email.
	 *
	 * @param lastLoginIP the last login ip of this otp email
	 */
	public void setLastLoginIP(String lastLoginIP);

	/**
	 * Returns the last failed login date of this otp email.
	 *
	 * @return the last failed login date of this otp email
	 */
	public Date getLastFailedLoginDate();

	/**
	 * Sets the last failed login date of this otp email.
	 *
	 * @param lastFailedLoginDate the last failed login date of this otp email
	 */
	public void setLastFailedLoginDate(Date lastFailedLoginDate);

	/**
	 * Returns the failed login attempts of this otp email.
	 *
	 * @return the failed login attempts of this otp email
	 */
	public int getFailedLoginAttempts();

	/**
	 * Sets the failed login attempts of this otp email.
	 *
	 * @param failedLoginAttempts the failed login attempts of this otp email
	 */
	public void setFailedLoginAttempts(int failedLoginAttempts);

	/**
	 * Returns the verified of this otp email.
	 *
	 * @return the verified of this otp email
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this otp email is verified.
	 *
	 * @return <code>true</code> if this otp email is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this otp email is verified.
	 *
	 * @param verified the verified of this otp email
	 */
	public void setVerified(boolean verified);
}