/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.otp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the OTP service. Represents a row in the &quot;OTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see OTP
 * @see com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPImpl
 * @see com.liferay.multi.factor.authentication.provider.otp.model.impl.OTPModelImpl
 * @generated
 */
@ProviderType
public interface OTPModel extends AuditedModel, BaseModel<OTP>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a otp model instance should use the {@link OTP} interface instead.
	 */

	/**
	 * Returns the primary key of this otp.
	 *
	 * @return the primary key of this otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this otp.
	 *
	 * @param primaryKey the primary key of this otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the otp ID of this otp.
	 *
	 * @return the otp ID of this otp
	 */
	public long getOtpId();

	/**
	 * Sets the otp ID of this otp.
	 *
	 * @param otpId the otp ID of this otp
	 */
	public void setOtpId(long otpId);

	/**
	 * Returns the company ID of this otp.
	 *
	 * @return the company ID of this otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this otp.
	 *
	 * @param companyId the company ID of this otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this otp.
	 *
	 * @return the user ID of this otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this otp.
	 *
	 * @param userId the user ID of this otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this otp.
	 *
	 * @return the user uuid of this otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this otp.
	 *
	 * @param userUuid the user uuid of this otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this otp.
	 *
	 * @return the user name of this otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this otp.
	 *
	 * @param userName the user name of this otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this otp.
	 *
	 * @return the create date of this otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this otp.
	 *
	 * @param createDate the create date of this otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this otp.
	 *
	 * @return the modified date of this otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this otp.
	 *
	 * @param modifiedDate the modified date of this otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this otp.
	 *
	 * @return the email address of this otp
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this otp.
	 *
	 * @param emailAddress the email address of this otp
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the last login date of this otp.
	 *
	 * @return the last login date of this otp
	 */
	public Date getLastLoginDate();

	/**
	 * Sets the last login date of this otp.
	 *
	 * @param lastLoginDate the last login date of this otp
	 */
	public void setLastLoginDate(Date lastLoginDate);

	/**
	 * Returns the last login ip of this otp.
	 *
	 * @return the last login ip of this otp
	 */
	@AutoEscape
	public String getLastLoginIP();

	/**
	 * Sets the last login ip of this otp.
	 *
	 * @param lastLoginIP the last login ip of this otp
	 */
	public void setLastLoginIP(String lastLoginIP);

	/**
	 * Returns the last failed login date of this otp.
	 *
	 * @return the last failed login date of this otp
	 */
	public Date getLastFailedLoginDate();

	/**
	 * Sets the last failed login date of this otp.
	 *
	 * @param lastFailedLoginDate the last failed login date of this otp
	 */
	public void setLastFailedLoginDate(Date lastFailedLoginDate);

	/**
	 * Returns the failed login attempts of this otp.
	 *
	 * @return the failed login attempts of this otp
	 */
	public int getFailedLoginAttempts();

	/**
	 * Sets the failed login attempts of this otp.
	 *
	 * @param failedLoginAttempts the failed login attempts of this otp
	 */
	public void setFailedLoginAttempts(int failedLoginAttempts);

	/**
	 * Returns the verified of this otp.
	 *
	 * @return the verified of this otp
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this otp is verified.
	 *
	 * @return <code>true</code> if this otp is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this otp is verified.
	 *
	 * @param verified the verified of this otp
	 */
	public void setVerified(boolean verified);
}