dependencies {
	compileOnly project(":apps:keymanager:keymanager-api")

	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.5.1"
	compileOnly group: "org.osgi", name: "org.osgi.service.metatype.annotations", version: "1.4.1"

	implementation group: "com.bettercloud", name: "vault-java-driver", version: "5.4.1"
}
