dependencies {
	compileInclude group: "com.bettercloud", name: "vault-java-driver", version: "5.1.0"

	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"

	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.metatype.annotations", version: "1.4.0"
	compileOnly project(":apps:keymanager:keymanager-api")
}