/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.time.otp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the TimeOTPEntry service. Represents a row in the &quot;TimeOTPEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multi.factor.authentication.provider.time.otp.model.impl.TimeOTPEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multi.factor.authentication.provider.time.otp.model.impl.TimeOTPEntryImpl</code>.
 * </p>
 *
 * @author arthurchan35
 * @see TimeOTPEntry
 * @generated
 */
@ProviderType
public interface TimeOTPEntryModel
	extends AuditedModel, BaseModel<TimeOTPEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a time otp entry model instance should use the {@link TimeOTPEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this time otp entry.
	 *
	 * @return the primary key of this time otp entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this time otp entry.
	 *
	 * @param primaryKey the primary key of this time otp entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this time otp entry.
	 *
	 * @return the entry ID of this time otp entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this time otp entry.
	 *
	 * @param entryId the entry ID of this time otp entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this time otp entry.
	 *
	 * @return the company ID of this time otp entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this time otp entry.
	 *
	 * @param companyId the company ID of this time otp entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this time otp entry.
	 *
	 * @return the user ID of this time otp entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this time otp entry.
	 *
	 * @param userId the user ID of this time otp entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this time otp entry.
	 *
	 * @return the user uuid of this time otp entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this time otp entry.
	 *
	 * @param userUuid the user uuid of this time otp entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this time otp entry.
	 *
	 * @return the user name of this time otp entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this time otp entry.
	 *
	 * @param userName the user name of this time otp entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this time otp entry.
	 *
	 * @return the create date of this time otp entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this time otp entry.
	 *
	 * @param createDate the create date of this time otp entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this time otp entry.
	 *
	 * @return the modified date of this time otp entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this time otp entry.
	 *
	 * @param modifiedDate the modified date of this time otp entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the shared secret of this time otp entry.
	 *
	 * @return the shared secret of this time otp entry
	 */
	@AutoEscape
	public String getSharedSecret();

	/**
	 * Sets the shared secret of this time otp entry.
	 *
	 * @param sharedSecret the shared secret of this time otp entry
	 */
	public void setSharedSecret(String sharedSecret);

	/**
	 * Returns the last success date of this time otp entry.
	 *
	 * @return the last success date of this time otp entry
	 */
	public Date getLastSuccessDate();

	/**
	 * Sets the last success date of this time otp entry.
	 *
	 * @param lastSuccessDate the last success date of this time otp entry
	 */
	public void setLastSuccessDate(Date lastSuccessDate);

	/**
	 * Returns the last success ip of this time otp entry.
	 *
	 * @return the last success ip of this time otp entry
	 */
	@AutoEscape
	public String getLastSuccessIP();

	/**
	 * Sets the last success ip of this time otp entry.
	 *
	 * @param lastSuccessIP the last success ip of this time otp entry
	 */
	public void setLastSuccessIP(String lastSuccessIP);

	/**
	 * Returns the last fail date of this time otp entry.
	 *
	 * @return the last fail date of this time otp entry
	 */
	public Date getLastFailDate();

	/**
	 * Sets the last fail date of this time otp entry.
	 *
	 * @param lastFailDate the last fail date of this time otp entry
	 */
	public void setLastFailDate(Date lastFailDate);

	/**
	 * Returns the last fail ip of this time otp entry.
	 *
	 * @return the last fail ip of this time otp entry
	 */
	@AutoEscape
	public String getLastFailIP();

	/**
	 * Sets the last fail ip of this time otp entry.
	 *
	 * @param lastFailIP the last fail ip of this time otp entry
	 */
	public void setLastFailIP(String lastFailIP);

	/**
	 * Returns the failed attempts of this time otp entry.
	 *
	 * @return the failed attempts of this time otp entry
	 */
	public int getFailedAttempts();

	/**
	 * Sets the failed attempts of this time otp entry.
	 *
	 * @param failedAttempts the failed attempts of this time otp entry
	 */
	public void setFailedAttempts(int failedAttempts);

}