dependencies {
	compileInclude group: "com.google.auth", name: "google-auth-library-oauth2-http", version: "1.23.0"
	compileInclude group: "com.google.cloud", name: "google-cloud-kms", version: "2.37.0"

	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.metatype.annotations", version: "1.4.0"
	compileOnly project(":apps:keymanager:keymanager-api")
}
