/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bemis.portal.twofa.device.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.bemis.portal.twofa.device.manager.model.DeviceCode;
import com.bemis.portal.twofa.device.manager.service.DeviceCodeLocalServiceUtil;

/**
 * The extended model base implementation for the DeviceCode service. Represents a row in the &quot;Bemis_DeviceCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceCodeImpl}.
 * </p>
 *
 * @author Prathima Shreenath
 * @see DeviceCodeImpl
 * @see DeviceCode
 * @generated
 */
@ProviderType
public abstract class DeviceCodeBaseImpl extends DeviceCodeModelImpl
	implements DeviceCode {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a device code model instance should use the {@link DeviceCode} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DeviceCodeLocalServiceUtil.addDeviceCode(this);
		}
		else {
			DeviceCodeLocalServiceUtil.updateDeviceCode(this);
		}
	}
}