/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.keymanager.provider.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KeyEntry service. Represents a row in the &quot;KeyManagerDB_KeyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.keymanager.provider.db.model.impl.KeyEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.keymanager.provider.db.model.impl.KeyEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeyEntry
 * @generated
 */
@ProviderType
public interface KeyEntryModel
	extends BaseModel<KeyEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a key entry model instance should use the {@link KeyEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this key entry.
	 *
	 * @return the primary key of this key entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this key entry.
	 *
	 * @param primaryKey the primary key of this key entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this key entry.
	 *
	 * @return the mvcc version of this key entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this key entry.
	 *
	 * @param mvccVersion the mvcc version of this key entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the key entry ID of this key entry.
	 *
	 * @return the key entry ID of this key entry
	 */
	public long getKeyEntryId();

	/**
	 * Sets the key entry ID of this key entry.
	 *
	 * @param keyEntryId the key entry ID of this key entry
	 */
	public void setKeyEntryId(long keyEntryId);

	/**
	 * Returns the company ID of this key entry.
	 *
	 * @return the company ID of this key entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this key entry.
	 *
	 * @param companyId the company ID of this key entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the alias of this key entry.
	 *
	 * @return the alias of this key entry
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this key entry.
	 *
	 * @param alias the alias of this key entry
	 */
	public void setAlias(String alias);

	/**
	 * Returns the key type of this key entry.
	 *
	 * @return the key type of this key entry
	 */
	@AutoEscape
	public String getKeyType();

	/**
	 * Sets the key type of this key entry.
	 *
	 * @param keyType the key type of this key entry
	 */
	public void setKeyType(String keyType);

	/**
	 * Returns the algorithm of this key entry.
	 *
	 * @return the algorithm of this key entry
	 */
	@AutoEscape
	public String getAlgorithm();

	/**
	 * Sets the algorithm of this key entry.
	 *
	 * @param algorithm the algorithm of this key entry
	 */
	public void setAlgorithm(String algorithm);

	/**
	 * Returns the cipher spec of this key entry.
	 *
	 * @return the cipher spec of this key entry
	 */
	@AutoEscape
	public String getCipherSpec();

	/**
	 * Sets the cipher spec of this key entry.
	 *
	 * @param cipherSpec the cipher spec of this key entry
	 */
	public void setCipherSpec(String cipherSpec);

	/**
	 * Returns the wrapped key blob of this key entry.
	 *
	 * @return the wrapped key blob of this key entry
	 */
	public Blob getWrappedKeyBlob();

	/**
	 * Sets the wrapped key blob of this key entry.
	 *
	 * @param wrappedKeyBlob the wrapped key blob of this key entry
	 */
	public void setWrappedKeyBlob(Blob wrappedKeyBlob);

	/**
	 * Returns the kek reference of this key entry.
	 *
	 * @return the kek reference of this key entry
	 */
	@AutoEscape
	public String getKekReference();

	/**
	 * Sets the kek reference of this key entry.
	 *
	 * @param kekReference the kek reference of this key entry
	 */
	public void setKekReference(String kekReference);

	/**
	 * Returns the create date of this key entry.
	 *
	 * @return the create date of this key entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this key entry.
	 *
	 * @param createDate the create date of this key entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this key entry.
	 *
	 * @return the modified date of this key entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this key entry.
	 *
	 * @param modifiedDate the modified date of this key entry
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public KeyEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}