/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.keymanager.provider.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SecretEntry service. Represents a row in the &quot;KeyManagerDB_SecretEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.keymanager.provider.db.model.impl.SecretEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.keymanager.provider.db.model.impl.SecretEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecretEntry
 * @generated
 */
@ProviderType
public interface SecretEntryModel
	extends BaseModel<SecretEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a secret entry model instance should use the {@link SecretEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this secret entry.
	 *
	 * @return the primary key of this secret entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this secret entry.
	 *
	 * @param primaryKey the primary key of this secret entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this secret entry.
	 *
	 * @return the mvcc version of this secret entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this secret entry.
	 *
	 * @param mvccVersion the mvcc version of this secret entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the secret entry ID of this secret entry.
	 *
	 * @return the secret entry ID of this secret entry
	 */
	public long getSecretEntryId();

	/**
	 * Sets the secret entry ID of this secret entry.
	 *
	 * @param secretEntryId the secret entry ID of this secret entry
	 */
	public void setSecretEntryId(long secretEntryId);

	/**
	 * Returns the company ID of this secret entry.
	 *
	 * @return the company ID of this secret entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this secret entry.
	 *
	 * @param companyId the company ID of this secret entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the alias of this secret entry.
	 *
	 * @return the alias of this secret entry
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this secret entry.
	 *
	 * @param alias the alias of this secret entry
	 */
	public void setAlias(String alias);

	/**
	 * Returns the ciphertext blob of this secret entry.
	 *
	 * @return the ciphertext blob of this secret entry
	 */
	public Blob getCiphertextBlob();

	/**
	 * Sets the ciphertext blob of this secret entry.
	 *
	 * @param ciphertextBlob the ciphertext blob of this secret entry
	 */
	public void setCiphertextBlob(Blob ciphertextBlob);

	/**
	 * Returns the iv of this secret entry.
	 *
	 * @return the iv of this secret entry
	 */
	@AutoEscape
	public String getIv();

	/**
	 * Sets the iv of this secret entry.
	 *
	 * @param iv the iv of this secret entry
	 */
	public void setIv(String iv);

	/**
	 * Returns the encrypted dek blob of this secret entry.
	 *
	 * @return the encrypted dek blob of this secret entry
	 */
	public Blob getEncryptedDEKBlob();

	/**
	 * Sets the encrypted dek blob of this secret entry.
	 *
	 * @param encryptedDEKBlob the encrypted dek blob of this secret entry
	 */
	public void setEncryptedDEKBlob(Blob encryptedDEKBlob);

	/**
	 * Returns the dek iv of this secret entry.
	 *
	 * @return the dek iv of this secret entry
	 */
	@AutoEscape
	public String getDekIv();

	/**
	 * Sets the dek iv of this secret entry.
	 *
	 * @param dekIv the dek iv of this secret entry
	 */
	public void setDekIv(String dekIv);

	/**
	 * Returns the kek reference of this secret entry.
	 *
	 * @return the kek reference of this secret entry
	 */
	@AutoEscape
	public String getKekReference();

	/**
	 * Sets the kek reference of this secret entry.
	 *
	 * @param kekReference the kek reference of this secret entry
	 */
	public void setKekReference(String kekReference);

	/**
	 * Returns the algorithm of this secret entry.
	 *
	 * @return the algorithm of this secret entry
	 */
	@AutoEscape
	public String getAlgorithm();

	/**
	 * Sets the algorithm of this secret entry.
	 *
	 * @param algorithm the algorithm of this secret entry
	 */
	public void setAlgorithm(String algorithm);

	/**
	 * Returns the create date of this secret entry.
	 *
	 * @return the create date of this secret entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this secret entry.
	 *
	 * @param createDate the create date of this secret entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this secret entry.
	 *
	 * @return the modified date of this secret entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this secret entry.
	 *
	 * @param modifiedDate the modified date of this secret entry
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public SecretEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}