/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.time.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.provider.time.otp.model.TimeOTPEntry;
import com.liferay.multi.factor.authentication.provider.time.otp.model.TimeOTPEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TimeOTPEntry service. Represents a row in the &quot;TimeOTPEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TimeOTPEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimeOTPEntryImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TimeOTPEntryImpl
 * @generated
 */
@ProviderType
public class TimeOTPEntryModelImpl
	extends BaseModelImpl<TimeOTPEntry> implements TimeOTPEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a time otp entry model instance should use the <code>TimeOTPEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "TimeOTPEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"entryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"sharedSecret", Types.VARCHAR}, {"lastSuccessDate", Types.TIMESTAMP},
		{"lastSuccessIP", Types.VARCHAR}, {"lastFailDate", Types.TIMESTAMP},
		{"lastFailIP", Types.VARCHAR}, {"failedAttempts", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sharedSecret", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSuccessDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastSuccessIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastFailIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("failedAttempts", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TimeOTPEntry (entryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,sharedSecret VARCHAR(75) null,lastSuccessDate DATE null,lastSuccessIP VARCHAR(75) null,lastFailDate DATE null,lastFailIP VARCHAR(75) null,failedAttempts INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table TimeOTPEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY timeOTPEntry.entryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TimeOTPEntry.entryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long USERID_COLUMN_BITMASK = 1L;

	public static final long ENTRYID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TimeOTPEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TimeOTPEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TimeOTPEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TimeOTPEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TimeOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimeOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TimeOTPEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TimeOTPEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TimeOTPEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TimeOTPEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TimeOTPEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TimeOTPEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TimeOTPEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TimeOTPEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TimeOTPEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TimeOTPEntry, Object>>();
		Map<String, BiConsumer<TimeOTPEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TimeOTPEntry, ?>>();

		attributeGetterFunctions.put("entryId", TimeOTPEntry::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<TimeOTPEntry, Long>)TimeOTPEntry::setEntryId);
		attributeGetterFunctions.put("companyId", TimeOTPEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TimeOTPEntry, Long>)TimeOTPEntry::setCompanyId);
		attributeGetterFunctions.put("userId", TimeOTPEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TimeOTPEntry, Long>)TimeOTPEntry::setUserId);
		attributeGetterFunctions.put("userName", TimeOTPEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TimeOTPEntry, String>)TimeOTPEntry::setUserName);
		attributeGetterFunctions.put("createDate", TimeOTPEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TimeOTPEntry, Date>)TimeOTPEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TimeOTPEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TimeOTPEntry, Date>)TimeOTPEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"sharedSecret", TimeOTPEntry::getSharedSecret);
		attributeSetterBiConsumers.put(
			"sharedSecret",
			(BiConsumer<TimeOTPEntry, String>)TimeOTPEntry::setSharedSecret);
		attributeGetterFunctions.put(
			"lastSuccessDate", TimeOTPEntry::getLastSuccessDate);
		attributeSetterBiConsumers.put(
			"lastSuccessDate",
			(BiConsumer<TimeOTPEntry, Date>)TimeOTPEntry::setLastSuccessDate);
		attributeGetterFunctions.put(
			"lastSuccessIP", TimeOTPEntry::getLastSuccessIP);
		attributeSetterBiConsumers.put(
			"lastSuccessIP",
			(BiConsumer<TimeOTPEntry, String>)TimeOTPEntry::setLastSuccessIP);
		attributeGetterFunctions.put(
			"lastFailDate", TimeOTPEntry::getLastFailDate);
		attributeSetterBiConsumers.put(
			"lastFailDate",
			(BiConsumer<TimeOTPEntry, Date>)TimeOTPEntry::setLastFailDate);
		attributeGetterFunctions.put("lastFailIP", TimeOTPEntry::getLastFailIP);
		attributeSetterBiConsumers.put(
			"lastFailIP",
			(BiConsumer<TimeOTPEntry, String>)TimeOTPEntry::setLastFailIP);
		attributeGetterFunctions.put(
			"failedAttempts", TimeOTPEntry::getFailedAttempts);
		attributeSetterBiConsumers.put(
			"failedAttempts",
			(BiConsumer<TimeOTPEntry, Integer>)TimeOTPEntry::setFailedAttempts);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getSharedSecret() {
		if (_sharedSecret == null) {
			return "";
		}
		else {
			return _sharedSecret;
		}
	}

	@Override
	public void setSharedSecret(String sharedSecret) {
		_sharedSecret = sharedSecret;
	}

	@Override
	public Date getLastSuccessDate() {
		return _lastSuccessDate;
	}

	@Override
	public void setLastSuccessDate(Date lastSuccessDate) {
		_lastSuccessDate = lastSuccessDate;
	}

	@Override
	public String getLastSuccessIP() {
		if (_lastSuccessIP == null) {
			return "";
		}
		else {
			return _lastSuccessIP;
		}
	}

	@Override
	public void setLastSuccessIP(String lastSuccessIP) {
		_lastSuccessIP = lastSuccessIP;
	}

	@Override
	public Date getLastFailDate() {
		return _lastFailDate;
	}

	@Override
	public void setLastFailDate(Date lastFailDate) {
		_lastFailDate = lastFailDate;
	}

	@Override
	public String getLastFailIP() {
		if (_lastFailIP == null) {
			return "";
		}
		else {
			return _lastFailIP;
		}
	}

	@Override
	public void setLastFailIP(String lastFailIP) {
		_lastFailIP = lastFailIP;
	}

	@Override
	public int getFailedAttempts() {
		return _failedAttempts;
	}

	@Override
	public void setFailedAttempts(int failedAttempts) {
		_failedAttempts = failedAttempts;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TimeOTPEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TimeOTPEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TimeOTPEntry)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimeOTPEntryImpl timeOTPEntryImpl = new TimeOTPEntryImpl();

		timeOTPEntryImpl.setEntryId(getEntryId());
		timeOTPEntryImpl.setCompanyId(getCompanyId());
		timeOTPEntryImpl.setUserId(getUserId());
		timeOTPEntryImpl.setUserName(getUserName());
		timeOTPEntryImpl.setCreateDate(getCreateDate());
		timeOTPEntryImpl.setModifiedDate(getModifiedDate());
		timeOTPEntryImpl.setSharedSecret(getSharedSecret());
		timeOTPEntryImpl.setLastSuccessDate(getLastSuccessDate());
		timeOTPEntryImpl.setLastSuccessIP(getLastSuccessIP());
		timeOTPEntryImpl.setLastFailDate(getLastFailDate());
		timeOTPEntryImpl.setLastFailIP(getLastFailIP());
		timeOTPEntryImpl.setFailedAttempts(getFailedAttempts());

		timeOTPEntryImpl.resetOriginalValues();

		return timeOTPEntryImpl;
	}

	@Override
	public int compareTo(TimeOTPEntry timeOTPEntry) {
		long primaryKey = timeOTPEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TimeOTPEntry)) {
			return false;
		}

		TimeOTPEntry timeOTPEntry = (TimeOTPEntry)obj;

		long primaryKey = timeOTPEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TimeOTPEntryModelImpl timeOTPEntryModelImpl = this;

		timeOTPEntryModelImpl._originalUserId = timeOTPEntryModelImpl._userId;

		timeOTPEntryModelImpl._setOriginalUserId = false;

		timeOTPEntryModelImpl._setModifiedDate = false;

		timeOTPEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TimeOTPEntry> toCacheModel() {
		TimeOTPEntryCacheModel timeOTPEntryCacheModel =
			new TimeOTPEntryCacheModel();

		timeOTPEntryCacheModel.entryId = getEntryId();

		timeOTPEntryCacheModel.companyId = getCompanyId();

		timeOTPEntryCacheModel.userId = getUserId();

		timeOTPEntryCacheModel.userName = getUserName();

		String userName = timeOTPEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			timeOTPEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			timeOTPEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			timeOTPEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			timeOTPEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			timeOTPEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		timeOTPEntryCacheModel.sharedSecret = getSharedSecret();

		String sharedSecret = timeOTPEntryCacheModel.sharedSecret;

		if ((sharedSecret != null) && (sharedSecret.length() == 0)) {
			timeOTPEntryCacheModel.sharedSecret = null;
		}

		Date lastSuccessDate = getLastSuccessDate();

		if (lastSuccessDate != null) {
			timeOTPEntryCacheModel.lastSuccessDate = lastSuccessDate.getTime();
		}
		else {
			timeOTPEntryCacheModel.lastSuccessDate = Long.MIN_VALUE;
		}

		timeOTPEntryCacheModel.lastSuccessIP = getLastSuccessIP();

		String lastSuccessIP = timeOTPEntryCacheModel.lastSuccessIP;

		if ((lastSuccessIP != null) && (lastSuccessIP.length() == 0)) {
			timeOTPEntryCacheModel.lastSuccessIP = null;
		}

		Date lastFailDate = getLastFailDate();

		if (lastFailDate != null) {
			timeOTPEntryCacheModel.lastFailDate = lastFailDate.getTime();
		}
		else {
			timeOTPEntryCacheModel.lastFailDate = Long.MIN_VALUE;
		}

		timeOTPEntryCacheModel.lastFailIP = getLastFailIP();

		String lastFailIP = timeOTPEntryCacheModel.lastFailIP;

		if ((lastFailIP != null) && (lastFailIP.length() == 0)) {
			timeOTPEntryCacheModel.lastFailIP = null;
		}

		timeOTPEntryCacheModel.failedAttempts = getFailedAttempts();

		return timeOTPEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TimeOTPEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TimeOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimeOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TimeOTPEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TimeOTPEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TimeOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimeOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TimeOTPEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TimeOTPEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TimeOTPEntry.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _entryId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _sharedSecret;
	private Date _lastSuccessDate;
	private String _lastSuccessIP;
	private Date _lastFailDate;
	private String _lastFailIP;
	private int _failedAttempts;
	private long _columnBitmask;
	private TimeOTPEntry _escapedModel;

}