/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.totp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.provider.totp.model.TOTP;
import com.liferay.multi.factor.authentication.provider.totp.model.TOTPModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TOTP service. Represents a row in the &quot;TOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TOTPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TOTPImpl
 * @generated
 */
@ProviderType
public class TOTPModelImpl extends BaseModelImpl<TOTP> implements TOTPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a totp model instance should use the <code>TOTP</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOTP";

	public static final Object[][] TABLE_COLUMNS = {
		{"totpId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"backupCodes", Types.VARCHAR}, {"lastLoginDate", Types.TIMESTAMP},
		{"lastLoginIP", Types.VARCHAR},
		{"lastFailedLoginDate", Types.TIMESTAMP},
		{"failedLoginAttempts", Types.INTEGER}, {"sharedSecret", Types.VARCHAR},
		{"verified", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("totpId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("backupCodes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastLoginDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastLoginIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailedLoginDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("failedLoginAttempts", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sharedSecret", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("verified", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOTP (totpId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,backupCodes VARCHAR(75) null,lastLoginDate DATE null,lastLoginIP VARCHAR(75) null,lastFailedLoginDate DATE null,failedLoginAttempts INTEGER,sharedSecret VARCHAR(75) null,verified BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table TOTP";

	public static final String ORDER_BY_JPQL = " ORDER BY totp.totpId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY TOTP.totpId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long USERID_COLUMN_BITMASK = 1L;

	public static final long TOTPID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TOTPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _totpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTotpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _totpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TOTP.class;
	}

	@Override
	public String getModelClassName() {
		return TOTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TOTP, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TOTP)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TOTP, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TOTP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((TOTP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TOTP, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TOTP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TOTP, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TOTP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TOTP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TOTP, Object>>();
		Map<String, BiConsumer<TOTP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TOTP, ?>>();

		attributeGetterFunctions.put("totpId", TOTP::getTotpId);
		attributeSetterBiConsumers.put(
			"totpId", (BiConsumer<TOTP, Long>)TOTP::setTotpId);
		attributeGetterFunctions.put("companyId", TOTP::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<TOTP, Long>)TOTP::setCompanyId);
		attributeGetterFunctions.put("userId", TOTP::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TOTP, Long>)TOTP::setUserId);
		attributeGetterFunctions.put("userName", TOTP::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<TOTP, String>)TOTP::setUserName);
		attributeGetterFunctions.put("createDate", TOTP::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<TOTP, Date>)TOTP::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", TOTP::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<TOTP, Date>)TOTP::setModifiedDate);
		attributeGetterFunctions.put("backupCodes", TOTP::getBackupCodes);
		attributeSetterBiConsumers.put(
			"backupCodes", (BiConsumer<TOTP, String>)TOTP::setBackupCodes);
		attributeGetterFunctions.put("lastLoginDate", TOTP::getLastLoginDate);
		attributeSetterBiConsumers.put(
			"lastLoginDate", (BiConsumer<TOTP, Date>)TOTP::setLastLoginDate);
		attributeGetterFunctions.put("lastLoginIP", TOTP::getLastLoginIP);
		attributeSetterBiConsumers.put(
			"lastLoginIP", (BiConsumer<TOTP, String>)TOTP::setLastLoginIP);
		attributeGetterFunctions.put(
			"lastFailedLoginDate", TOTP::getLastFailedLoginDate);
		attributeSetterBiConsumers.put(
			"lastFailedLoginDate",
			(BiConsumer<TOTP, Date>)TOTP::setLastFailedLoginDate);
		attributeGetterFunctions.put(
			"failedLoginAttempts", TOTP::getFailedLoginAttempts);
		attributeSetterBiConsumers.put(
			"failedLoginAttempts",
			(BiConsumer<TOTP, Integer>)TOTP::setFailedLoginAttempts);
		attributeGetterFunctions.put("sharedSecret", TOTP::getSharedSecret);
		attributeSetterBiConsumers.put(
			"sharedSecret", (BiConsumer<TOTP, String>)TOTP::setSharedSecret);
		attributeGetterFunctions.put("verified", TOTP::getVerified);
		attributeSetterBiConsumers.put(
			"verified", (BiConsumer<TOTP, Boolean>)TOTP::setVerified);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTotpId() {
		return _totpId;
	}

	@Override
	public void setTotpId(long totpId) {
		_totpId = totpId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getBackupCodes() {
		if (_backupCodes == null) {
			return "";
		}
		else {
			return _backupCodes;
		}
	}

	@Override
	public void setBackupCodes(String backupCodes) {
		_backupCodes = backupCodes;
	}

	@Override
	public Date getLastLoginDate() {
		return _lastLoginDate;
	}

	@Override
	public void setLastLoginDate(Date lastLoginDate) {
		_lastLoginDate = lastLoginDate;
	}

	@Override
	public String getLastLoginIP() {
		if (_lastLoginIP == null) {
			return "";
		}
		else {
			return _lastLoginIP;
		}
	}

	@Override
	public void setLastLoginIP(String lastLoginIP) {
		_lastLoginIP = lastLoginIP;
	}

	@Override
	public Date getLastFailedLoginDate() {
		return _lastFailedLoginDate;
	}

	@Override
	public void setLastFailedLoginDate(Date lastFailedLoginDate) {
		_lastFailedLoginDate = lastFailedLoginDate;
	}

	@Override
	public int getFailedLoginAttempts() {
		return _failedLoginAttempts;
	}

	@Override
	public void setFailedLoginAttempts(int failedLoginAttempts) {
		_failedLoginAttempts = failedLoginAttempts;
	}

	@Override
	public String getSharedSecret() {
		if (_sharedSecret == null) {
			return "";
		}
		else {
			return _sharedSecret;
		}
	}

	@Override
	public void setSharedSecret(String sharedSecret) {
		_sharedSecret = sharedSecret;
	}

	@Override
	public boolean getVerified() {
		return _verified;
	}

	@Override
	public boolean isVerified() {
		return _verified;
	}

	@Override
	public void setVerified(boolean verified) {
		_verified = verified;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TOTP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TOTP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TOTP)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TOTPImpl totpImpl = new TOTPImpl();

		totpImpl.setTotpId(getTotpId());
		totpImpl.setCompanyId(getCompanyId());
		totpImpl.setUserId(getUserId());
		totpImpl.setUserName(getUserName());
		totpImpl.setCreateDate(getCreateDate());
		totpImpl.setModifiedDate(getModifiedDate());
		totpImpl.setBackupCodes(getBackupCodes());
		totpImpl.setLastLoginDate(getLastLoginDate());
		totpImpl.setLastLoginIP(getLastLoginIP());
		totpImpl.setLastFailedLoginDate(getLastFailedLoginDate());
		totpImpl.setFailedLoginAttempts(getFailedLoginAttempts());
		totpImpl.setSharedSecret(getSharedSecret());
		totpImpl.setVerified(isVerified());

		totpImpl.resetOriginalValues();

		return totpImpl;
	}

	@Override
	public int compareTo(TOTP totp) {
		long primaryKey = totp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TOTP)) {
			return false;
		}

		TOTP totp = (TOTP)obj;

		long primaryKey = totp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TOTPModelImpl totpModelImpl = this;

		totpModelImpl._originalUserId = totpModelImpl._userId;

		totpModelImpl._setOriginalUserId = false;

		totpModelImpl._setModifiedDate = false;

		totpModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TOTP> toCacheModel() {
		TOTPCacheModel totpCacheModel = new TOTPCacheModel();

		totpCacheModel.totpId = getTotpId();

		totpCacheModel.companyId = getCompanyId();

		totpCacheModel.userId = getUserId();

		totpCacheModel.userName = getUserName();

		String userName = totpCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			totpCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			totpCacheModel.createDate = createDate.getTime();
		}
		else {
			totpCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			totpCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			totpCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		totpCacheModel.backupCodes = getBackupCodes();

		String backupCodes = totpCacheModel.backupCodes;

		if ((backupCodes != null) && (backupCodes.length() == 0)) {
			totpCacheModel.backupCodes = null;
		}

		Date lastLoginDate = getLastLoginDate();

		if (lastLoginDate != null) {
			totpCacheModel.lastLoginDate = lastLoginDate.getTime();
		}
		else {
			totpCacheModel.lastLoginDate = Long.MIN_VALUE;
		}

		totpCacheModel.lastLoginIP = getLastLoginIP();

		String lastLoginIP = totpCacheModel.lastLoginIP;

		if ((lastLoginIP != null) && (lastLoginIP.length() == 0)) {
			totpCacheModel.lastLoginIP = null;
		}

		Date lastFailedLoginDate = getLastFailedLoginDate();

		if (lastFailedLoginDate != null) {
			totpCacheModel.lastFailedLoginDate = lastFailedLoginDate.getTime();
		}
		else {
			totpCacheModel.lastFailedLoginDate = Long.MIN_VALUE;
		}

		totpCacheModel.failedLoginAttempts = getFailedLoginAttempts();

		totpCacheModel.sharedSecret = getSharedSecret();

		String sharedSecret = totpCacheModel.sharedSecret;

		if ((sharedSecret != null) && (sharedSecret.length() == 0)) {
			totpCacheModel.sharedSecret = null;
		}

		totpCacheModel.verified = isVerified();

		return totpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TOTP, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TOTP)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TOTP, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TOTP)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TOTP.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TOTP.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _totpId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _backupCodes;
	private Date _lastLoginDate;
	private String _lastLoginIP;
	private Date _lastFailedLoginDate;
	private int _failedLoginAttempts;
	private String _sharedSecret;
	private boolean _verified;
	private long _columnBitmask;
	private TOTP _escapedModel;

}