apply plugin: "com.liferay.lang.merger"

buildService {
	apiDir = "../journal-api/src/main/java"
	testDir = "../journal-test/src/testIntegration/java"
}

dependencies {
	provided group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	provided group: "com.liferay", name: "com.liferay.dynamic.data.mapping.api", version: "3.0.0"
	provided group: "com.liferay", name: "com.liferay.dynamic.data.mapping.service", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.exportimport.api", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.exportimport.service", version: "3.0.0"
	provided group: "com.liferay", name: "com.liferay.journal.lang", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.mobile.device.rules.api", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.osgi.service.tracker.collections", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.petra.collection", version: "1.0.0"
	provided group: "com.liferay", name: "com.liferay.petra.content", version: "1.0.0"
	provided group: "com.liferay", name: "com.liferay.petra.xml", version: "1.0.0"
	provided group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.portal.dao.orm.custom.sql", version: "1.0.0"
	provided group: "com.liferay", name: "com.liferay.portal.instance.lifecycle", version: "3.0.0"
	provided group: "com.liferay", name: "com.liferay.portal.spring.extender", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.portal.upgrade", version: "2.0.0"
	provided group: "com.liferay", name: "com.liferay.registry.api", version: "1.0.0"
	provided group: "com.liferay", name: "com.liferay.xstream.configurator.api", version: "2.0.0"
	provided group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "2.0.0"
	provided group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	provided group: "com.liferay.portal", name: "com.liferay.util.java", version: "2.0.0"
	provided group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "2.0.0"
	provided group: "commons-lang", name: "commons-lang", version: "2.1"
	provided group: "javax.portlet", name: "portlet-api", version: "2.0"
	provided group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	provided group: "javax.servlet.jsp", name: "javax.servlet.jsp-api", version: "2.3.1"
	provided group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	provided group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
	provided project(":apps:web-experience:journal:journal-api")
}

dependencies {
	findbugs 'com.google.code.findbugs:findbugs:3.0.1'
	findbugs configurations.findbugsPlugins.dependencies
	findbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.4.7-SNAPSHOT'
}

apply plugin: 'findbugs'

task copyFindbugSources(type: Copy, dependsOn: [generateJSPJava]) {
	from 'src/main/java'
	from "$project.buildDir/jspc"

	into "$project.buildDir/findbugs-src"
}

task copyFindbugClasses(type: Copy, dependsOn: [classes, compileJSP]) {
	from "$project.buildDir/unzipped-jar/"
	from "$project.buildDir/tmp/compileJSP/"

	into "$project.buildDir/findbugs-classes/"
}

task findSecurityBugs(type: FindBugs, dependsOn: [classes, compileJSP, copyFindbugSources, copyFindbugClasses]) {
	classes = fileTree("$project.buildDir/findbugs-classes/").include("**/*.class");
	source = files("$project.buildDir/findbugs-src/");
	classpath = files(sourceSets.main.compileClasspath)
	pluginClasspath = project.configurations.findbugsPlugins

	jvmArgs = [
			"-Dfindsecbugs.taint.customconfigfile=liferay.txt:find-security-bugs-false-positives.txt",
			"-Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector=sql-liferay.txt|SQL_INJECTION_HIBERNATE",
//			"-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005",
			"-Dfindsecbugs.taint.outputsummaries=true"]

	maxHeapSize = "3g"

	findbugs {
		toolVersion = "3.0.1"
		ignoreFailures = true
		reportsDir = file("$project.buildDir/findbugsReports")
		effort = "max"
		reportLevel = "low"
		includeFilter = file("$project.rootDir/fsb-include.xml")
		excludeFilter = file("$project.rootDir/fsb-exclude.xml")
		reports {
			// Only one of HTML or XML can be turned on at the same time
			html.enabled = true
			xml.enabled = !html.enabled
			xml.withMessages = false
		}
	}
}
