/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.otp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

/**
 * The base model interface for the TOTP service. Represents a row in the &quot;TOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.multi.factor.authentication.otp.model.impl.TOTPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.multi.factor.authentication.otp.model.impl.TOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TOTP
 * @see com.liferay.multi.factor.authentication.otp.model.impl.TOTPImpl
 * @see com.liferay.multi.factor.authentication.otp.model.impl.TOTPModelImpl
 * @generated
 */
@ProviderType
public interface TOTPModel extends BaseModel<TOTP> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a totp model instance should use the {@link TOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this totp.
	 *
	 * @return the primary key of this totp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this totp.
	 *
	 * @param primaryKey the primary key of this totp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the totp ID of this totp.
	 *
	 * @return the totp ID of this totp
	 */
	public long getTotpId();

	/**
	 * Sets the totp ID of this totp.
	 *
	 * @param totpId the totp ID of this totp
	 */
	public void setTotpId(long totpId);

	/**
	 * Returns the user ID of this totp.
	 *
	 * @return the user ID of this totp
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this totp.
	 *
	 * @param userId the user ID of this totp
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this totp.
	 *
	 * @return the user uuid of this totp
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this totp.
	 *
	 * @param userUuid the user uuid of this totp
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the failed attempts of this totp.
	 *
	 * @return the failed attempts of this totp
	 */
	public int getFailedAttempts();

	/**
	 * Sets the failed attempts of this totp.
	 *
	 * @param failedAttempts the failed attempts of this totp
	 */
	public void setFailedAttempts(int failedAttempts);

	/**
	 * Returns the shared secret of this totp.
	 *
	 * @return the shared secret of this totp
	 */
	@AutoEscape
	public String getSharedSecret();

	/**
	 * Sets the shared secret of this totp.
	 *
	 * @param sharedSecret the shared secret of this totp
	 */
	public void setSharedSecret(String sharedSecret);

	/**
	 * Returns the verified of this totp.
	 *
	 * @return the verified of this totp
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this totp is verified.
	 *
	 * @return <code>true</code> if this totp is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this totp is verified.
	 *
	 * @param verified the verified of this totp
	 */
	public void setVerified(boolean verified);
}