/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.multi.factor.authentication.otp.model.HOTP;
import com.liferay.multi.factor.authentication.otp.service.HOTPLocalServiceUtil;

/**
 * The extended model base implementation for the HOTP service. Represents a row in the &quot;HOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see HOTPImpl
 * @see HOTP
 * @generated
 */
@ProviderType
public abstract class HOTPBaseImpl extends HOTPModelImpl implements HOTP {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hotp model instance should use the {@link HOTP} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			HOTPLocalServiceUtil.addHOTP(this);
		}
		else {
			HOTPLocalServiceUtil.updateHOTP(this);
		}
	}
}