/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.totp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the TOTP service. Represents a row in the &quot;TOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.multi.factor.authentication.provider.totp.model.impl.TOTPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.multi.factor.authentication.provider.totp.model.impl.TOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TOTP
 * @see com.liferay.multi.factor.authentication.provider.totp.model.impl.TOTPImpl
 * @see com.liferay.multi.factor.authentication.provider.totp.model.impl.TOTPModelImpl
 * @generated
 */
@ProviderType
public interface TOTPModel extends AuditedModel, BaseModel<TOTP>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a totp model instance should use the {@link TOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this totp.
	 *
	 * @return the primary key of this totp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this totp.
	 *
	 * @param primaryKey the primary key of this totp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the totp ID of this totp.
	 *
	 * @return the totp ID of this totp
	 */
	public long getTotpId();

	/**
	 * Sets the totp ID of this totp.
	 *
	 * @param totpId the totp ID of this totp
	 */
	public void setTotpId(long totpId);

	/**
	 * Returns the company ID of this totp.
	 *
	 * @return the company ID of this totp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this totp.
	 *
	 * @param companyId the company ID of this totp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this totp.
	 *
	 * @return the user ID of this totp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this totp.
	 *
	 * @param userId the user ID of this totp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this totp.
	 *
	 * @return the user uuid of this totp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this totp.
	 *
	 * @param userUuid the user uuid of this totp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this totp.
	 *
	 * @return the user name of this totp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this totp.
	 *
	 * @param userName the user name of this totp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this totp.
	 *
	 * @return the create date of this totp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this totp.
	 *
	 * @param createDate the create date of this totp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this totp.
	 *
	 * @return the modified date of this totp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this totp.
	 *
	 * @param modifiedDate the modified date of this totp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the backup codes of this totp.
	 *
	 * @return the backup codes of this totp
	 */
	@AutoEscape
	public String getBackupCodes();

	/**
	 * Sets the backup codes of this totp.
	 *
	 * @param backupCodes the backup codes of this totp
	 */
	public void setBackupCodes(String backupCodes);

	/**
	 * Returns the last login date of this totp.
	 *
	 * @return the last login date of this totp
	 */
	public Date getLastLoginDate();

	/**
	 * Sets the last login date of this totp.
	 *
	 * @param lastLoginDate the last login date of this totp
	 */
	public void setLastLoginDate(Date lastLoginDate);

	/**
	 * Returns the last login ip of this totp.
	 *
	 * @return the last login ip of this totp
	 */
	@AutoEscape
	public String getLastLoginIP();

	/**
	 * Sets the last login ip of this totp.
	 *
	 * @param lastLoginIP the last login ip of this totp
	 */
	public void setLastLoginIP(String lastLoginIP);

	/**
	 * Returns the last failed login date of this totp.
	 *
	 * @return the last failed login date of this totp
	 */
	public Date getLastFailedLoginDate();

	/**
	 * Sets the last failed login date of this totp.
	 *
	 * @param lastFailedLoginDate the last failed login date of this totp
	 */
	public void setLastFailedLoginDate(Date lastFailedLoginDate);

	/**
	 * Returns the failed login attempts of this totp.
	 *
	 * @return the failed login attempts of this totp
	 */
	public int getFailedLoginAttempts();

	/**
	 * Sets the failed login attempts of this totp.
	 *
	 * @param failedLoginAttempts the failed login attempts of this totp
	 */
	public void setFailedLoginAttempts(int failedLoginAttempts);

	/**
	 * Returns the shared secret of this totp.
	 *
	 * @return the shared secret of this totp
	 */
	@AutoEscape
	public String getSharedSecret();

	/**
	 * Sets the shared secret of this totp.
	 *
	 * @param sharedSecret the shared secret of this totp
	 */
	public void setSharedSecret(String sharedSecret);

	/**
	 * Returns the verified of this totp.
	 *
	 * @return the verified of this totp
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this totp is verified.
	 *
	 * @return <code>true</code> if this totp is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this totp is verified.
	 *
	 * @param verified the verified of this totp
	 */
	public void setVerified(boolean verified);
}