/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.email.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP;
import com.liferay.multi.factor.authentication.provider.email.otp.service.EmailOTPLocalServiceUtil;

/**
 * The extended model base implementation for the EmailOTP service. Represents a row in the &quot;EmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see EmailOTPImpl
 * @see EmailOTP
 * @generated
 */
@ProviderType
public abstract class EmailOTPBaseImpl
	extends EmailOTPModelImpl implements EmailOTP {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email otp model instance should use the <code>EmailOTP</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmailOTPLocalServiceUtil.addEmailOTP(this);
		}
		else {
			EmailOTPLocalServiceUtil.updateEmailOTP(this);
		}
	}

}