/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.email.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP;
import com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTPModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmailOTP service. Represents a row in the &quot;EmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EmailOTPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see EmailOTPImpl
 * @generated
 */
@ProviderType
public class EmailOTPModelImpl
	extends BaseModelImpl<EmailOTP> implements EmailOTPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email otp model instance should use the <code>EmailOTP</code> interface instead.
	 */
	public static final String TABLE_NAME = "EmailOTP";

	public static final Object[][] TABLE_COLUMNS = {
		{"emailOTPId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"emailAddress", Types.VARCHAR}, {"lastSuccessDate", Types.TIMESTAMP},
		{"lastSuccessIP", Types.VARCHAR}, {"lastFailDate", Types.TIMESTAMP},
		{"lastFailIP", Types.VARCHAR}, {"failedAttempts", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("emailOTPId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSuccessDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastSuccessIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastFailIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("failedAttempts", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EmailOTP (emailOTPId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,emailAddress VARCHAR(75) null,lastSuccessDate DATE null,lastSuccessIP VARCHAR(75) null,lastFailDate DATE null,lastFailIP VARCHAR(75) null,failedAttempts INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table EmailOTP";

	public static final String ORDER_BY_JPQL =
		" ORDER BY emailOTP.emailOTPId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EmailOTP.emailOTPId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.multi.factor.authentication.provider.email.otp.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.multi.factor.authentication.provider.email.otp.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.multi.factor.authentication.provider.email.otp.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
		true);

	public static final long USERID_COLUMN_BITMASK = 1L;

	public static final long EMAILOTPID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.multi.factor.authentication.provider.email.otp.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"));

	public EmailOTPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _emailOTPId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmailOTPId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _emailOTPId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmailOTP.class;
	}

	@Override
	public String getModelClassName() {
		return EmailOTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((EmailOTP)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmailOTP, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmailOTP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmailOTP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmailOTP, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmailOTP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EmailOTP, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmailOTP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmailOTP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EmailOTP, Object>>();
		Map<String, BiConsumer<EmailOTP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EmailOTP, ?>>();

		attributeGetterFunctions.put("emailOTPId", EmailOTP::getEmailOTPId);
		attributeSetterBiConsumers.put(
			"emailOTPId", (BiConsumer<EmailOTP, Long>)EmailOTP::setEmailOTPId);
		attributeGetterFunctions.put("companyId", EmailOTP::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<EmailOTP, Long>)EmailOTP::setCompanyId);
		attributeGetterFunctions.put("userId", EmailOTP::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<EmailOTP, Long>)EmailOTP::setUserId);
		attributeGetterFunctions.put("userName", EmailOTP::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<EmailOTP, String>)EmailOTP::setUserName);
		attributeGetterFunctions.put("createDate", EmailOTP::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<EmailOTP, Date>)EmailOTP::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", EmailOTP::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmailOTP, Date>)EmailOTP::setModifiedDate);
		attributeGetterFunctions.put("emailAddress", EmailOTP::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<EmailOTP, String>)EmailOTP::setEmailAddress);
		attributeGetterFunctions.put(
			"lastSuccessDate", EmailOTP::getLastSuccessDate);
		attributeSetterBiConsumers.put(
			"lastSuccessDate",
			(BiConsumer<EmailOTP, Date>)EmailOTP::setLastSuccessDate);
		attributeGetterFunctions.put(
			"lastSuccessIP", EmailOTP::getLastSuccessIP);
		attributeSetterBiConsumers.put(
			"lastSuccessIP",
			(BiConsumer<EmailOTP, String>)EmailOTP::setLastSuccessIP);
		attributeGetterFunctions.put("lastFailDate", EmailOTP::getLastFailDate);
		attributeSetterBiConsumers.put(
			"lastFailDate",
			(BiConsumer<EmailOTP, Date>)EmailOTP::setLastFailDate);
		attributeGetterFunctions.put("lastFailIP", EmailOTP::getLastFailIP);
		attributeSetterBiConsumers.put(
			"lastFailIP",
			(BiConsumer<EmailOTP, String>)EmailOTP::setLastFailIP);
		attributeGetterFunctions.put(
			"failedAttempts", EmailOTP::getFailedAttempts);
		attributeSetterBiConsumers.put(
			"failedAttempts",
			(BiConsumer<EmailOTP, Integer>)EmailOTP::setFailedAttempts);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEmailOTPId() {
		return _emailOTPId;
	}

	@Override
	public void setEmailOTPId(long emailOTPId) {
		_emailOTPId = emailOTPId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_emailAddress = emailAddress;
	}

	@Override
	public Date getLastSuccessDate() {
		return _lastSuccessDate;
	}

	@Override
	public void setLastSuccessDate(Date lastSuccessDate) {
		_lastSuccessDate = lastSuccessDate;
	}

	@Override
	public String getLastSuccessIP() {
		if (_lastSuccessIP == null) {
			return "";
		}
		else {
			return _lastSuccessIP;
		}
	}

	@Override
	public void setLastSuccessIP(String lastSuccessIP) {
		_lastSuccessIP = lastSuccessIP;
	}

	@Override
	public Date getLastFailDate() {
		return _lastFailDate;
	}

	@Override
	public void setLastFailDate(Date lastFailDate) {
		_lastFailDate = lastFailDate;
	}

	@Override
	public String getLastFailIP() {
		if (_lastFailIP == null) {
			return "";
		}
		else {
			return _lastFailIP;
		}
	}

	@Override
	public void setLastFailIP(String lastFailIP) {
		_lastFailIP = lastFailIP;
	}

	@Override
	public int getFailedAttempts() {
		return _failedAttempts;
	}

	@Override
	public void setFailedAttempts(int failedAttempts) {
		_failedAttempts = failedAttempts;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmailOTP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmailOTP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmailOTP)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmailOTPImpl emailOTPImpl = new EmailOTPImpl();

		emailOTPImpl.setEmailOTPId(getEmailOTPId());
		emailOTPImpl.setCompanyId(getCompanyId());
		emailOTPImpl.setUserId(getUserId());
		emailOTPImpl.setUserName(getUserName());
		emailOTPImpl.setCreateDate(getCreateDate());
		emailOTPImpl.setModifiedDate(getModifiedDate());
		emailOTPImpl.setEmailAddress(getEmailAddress());
		emailOTPImpl.setLastSuccessDate(getLastSuccessDate());
		emailOTPImpl.setLastSuccessIP(getLastSuccessIP());
		emailOTPImpl.setLastFailDate(getLastFailDate());
		emailOTPImpl.setLastFailIP(getLastFailIP());
		emailOTPImpl.setFailedAttempts(getFailedAttempts());

		emailOTPImpl.resetOriginalValues();

		return emailOTPImpl;
	}

	@Override
	public int compareTo(EmailOTP emailOTP) {
		long primaryKey = emailOTP.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmailOTP)) {
			return false;
		}

		EmailOTP emailOTP = (EmailOTP)obj;

		long primaryKey = emailOTP.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EmailOTPModelImpl emailOTPModelImpl = this;

		emailOTPModelImpl._originalUserId = emailOTPModelImpl._userId;

		emailOTPModelImpl._setOriginalUserId = false;

		emailOTPModelImpl._setModifiedDate = false;

		emailOTPModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmailOTP> toCacheModel() {
		EmailOTPCacheModel emailOTPCacheModel = new EmailOTPCacheModel();

		emailOTPCacheModel.emailOTPId = getEmailOTPId();

		emailOTPCacheModel.companyId = getCompanyId();

		emailOTPCacheModel.userId = getUserId();

		emailOTPCacheModel.userName = getUserName();

		String userName = emailOTPCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			emailOTPCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			emailOTPCacheModel.createDate = createDate.getTime();
		}
		else {
			emailOTPCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			emailOTPCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			emailOTPCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.emailAddress = getEmailAddress();

		String emailAddress = emailOTPCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			emailOTPCacheModel.emailAddress = null;
		}

		Date lastSuccessDate = getLastSuccessDate();

		if (lastSuccessDate != null) {
			emailOTPCacheModel.lastSuccessDate = lastSuccessDate.getTime();
		}
		else {
			emailOTPCacheModel.lastSuccessDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.lastSuccessIP = getLastSuccessIP();

		String lastSuccessIP = emailOTPCacheModel.lastSuccessIP;

		if ((lastSuccessIP != null) && (lastSuccessIP.length() == 0)) {
			emailOTPCacheModel.lastSuccessIP = null;
		}

		Date lastFailDate = getLastFailDate();

		if (lastFailDate != null) {
			emailOTPCacheModel.lastFailDate = lastFailDate.getTime();
		}
		else {
			emailOTPCacheModel.lastFailDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.lastFailIP = getLastFailIP();

		String lastFailIP = emailOTPCacheModel.lastFailIP;

		if ((lastFailIP != null) && (lastFailIP.length() == 0)) {
			emailOTPCacheModel.lastFailIP = null;
		}

		emailOTPCacheModel.failedAttempts = getFailedAttempts();

		return emailOTPCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EmailOTP)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EmailOTP)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		EmailOTP.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		EmailOTP.class, ModelWrapper.class
	};

	private long _emailOTPId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _emailAddress;
	private Date _lastSuccessDate;
	private String _lastSuccessIP;
	private Date _lastFailDate;
	private String _lastFailIP;
	private int _failedAttempts;
	private long _columnBitmask;
	private EmailOTP _escapedModel;

}