/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.provider.email.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP;
import com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTPModel;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmailOTP service. Represents a row in the &quot;EmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EmailOTPModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see EmailOTPImpl
 * @see EmailOTP
 * @see EmailOTPModel
 * @generated
 */
@ProviderType
public class EmailOTPModelImpl extends BaseModelImpl<EmailOTP>
	implements EmailOTPModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email otp model instance should use the {@link EmailOTP} interface instead.
	 */
	public static final String TABLE_NAME = "EmailOTP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "emailOTPId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "emailAddress", Types.VARCHAR },
			{ "lastSuccessDate", Types.TIMESTAMP },
			{ "lastSuccessIP", Types.VARCHAR },
			{ "lastFailDate", Types.TIMESTAMP },
			{ "lastFailIP", Types.VARCHAR },
			{ "failedAttempts", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("emailOTPId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSuccessDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastSuccessIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastFailIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("failedAttempts", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table EmailOTP (emailOTPId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,emailAddress VARCHAR(75) null,lastSuccessDate DATE null,lastSuccessIP VARCHAR(75) null,lastFailDate DATE null,lastFailIP VARCHAR(75) null,failedAttempts INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table EmailOTP";
	public static final String ORDER_BY_JPQL = " ORDER BY emailOTP.emailOTPId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EmailOTP.emailOTPId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.multi.factor.authentication.provider.email.otp.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.multi.factor.authentication.provider.email.otp.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.multi.factor.authentication.provider.email.otp.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"),
			true);
	public static final long USERID_COLUMN_BITMASK = 1L;
	public static final long EMAILOTPID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.multi.factor.authentication.provider.email.otp.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP"));

	public EmailOTPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _emailOTPId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmailOTPId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _emailOTPId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmailOTP.class;
	}

	@Override
	public String getModelClassName() {
		return EmailOTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("emailOTPId", getEmailOTPId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("emailAddress", getEmailAddress());
		attributes.put("lastSuccessDate", getLastSuccessDate());
		attributes.put("lastSuccessIP", getLastSuccessIP());
		attributes.put("lastFailDate", getLastFailDate());
		attributes.put("lastFailIP", getLastFailIP());
		attributes.put("failedAttempts", getFailedAttempts());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long emailOTPId = (Long)attributes.get("emailOTPId");

		if (emailOTPId != null) {
			setEmailOTPId(emailOTPId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String emailAddress = (String)attributes.get("emailAddress");

		if (emailAddress != null) {
			setEmailAddress(emailAddress);
		}

		Date lastSuccessDate = (Date)attributes.get("lastSuccessDate");

		if (lastSuccessDate != null) {
			setLastSuccessDate(lastSuccessDate);
		}

		String lastSuccessIP = (String)attributes.get("lastSuccessIP");

		if (lastSuccessIP != null) {
			setLastSuccessIP(lastSuccessIP);
		}

		Date lastFailDate = (Date)attributes.get("lastFailDate");

		if (lastFailDate != null) {
			setLastFailDate(lastFailDate);
		}

		String lastFailIP = (String)attributes.get("lastFailIP");

		if (lastFailIP != null) {
			setLastFailIP(lastFailIP);
		}

		Integer failedAttempts = (Integer)attributes.get("failedAttempts");

		if (failedAttempts != null) {
			setFailedAttempts(failedAttempts);
		}
	}

	@Override
	public long getEmailOTPId() {
		return _emailOTPId;
	}

	@Override
	public void setEmailOTPId(long emailOTPId) {
		_emailOTPId = emailOTPId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_emailAddress = emailAddress;
	}

	@Override
	public Date getLastSuccessDate() {
		return _lastSuccessDate;
	}

	@Override
	public void setLastSuccessDate(Date lastSuccessDate) {
		_lastSuccessDate = lastSuccessDate;
	}

	@Override
	public String getLastSuccessIP() {
		if (_lastSuccessIP == null) {
			return "";
		}
		else {
			return _lastSuccessIP;
		}
	}

	@Override
	public void setLastSuccessIP(String lastSuccessIP) {
		_lastSuccessIP = lastSuccessIP;
	}

	@Override
	public Date getLastFailDate() {
		return _lastFailDate;
	}

	@Override
	public void setLastFailDate(Date lastFailDate) {
		_lastFailDate = lastFailDate;
	}

	@Override
	public String getLastFailIP() {
		if (_lastFailIP == null) {
			return "";
		}
		else {
			return _lastFailIP;
		}
	}

	@Override
	public void setLastFailIP(String lastFailIP) {
		_lastFailIP = lastFailIP;
	}

	@Override
	public int getFailedAttempts() {
		return _failedAttempts;
	}

	@Override
	public void setFailedAttempts(int failedAttempts) {
		_failedAttempts = failedAttempts;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmailOTP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmailOTP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmailOTP)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmailOTPImpl emailOTPImpl = new EmailOTPImpl();

		emailOTPImpl.setEmailOTPId(getEmailOTPId());
		emailOTPImpl.setCompanyId(getCompanyId());
		emailOTPImpl.setUserId(getUserId());
		emailOTPImpl.setUserName(getUserName());
		emailOTPImpl.setCreateDate(getCreateDate());
		emailOTPImpl.setModifiedDate(getModifiedDate());
		emailOTPImpl.setEmailAddress(getEmailAddress());
		emailOTPImpl.setLastSuccessDate(getLastSuccessDate());
		emailOTPImpl.setLastSuccessIP(getLastSuccessIP());
		emailOTPImpl.setLastFailDate(getLastFailDate());
		emailOTPImpl.setLastFailIP(getLastFailIP());
		emailOTPImpl.setFailedAttempts(getFailedAttempts());

		emailOTPImpl.resetOriginalValues();

		return emailOTPImpl;
	}

	@Override
	public int compareTo(EmailOTP emailOTP) {
		long primaryKey = emailOTP.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmailOTP)) {
			return false;
		}

		EmailOTP emailOTP = (EmailOTP)obj;

		long primaryKey = emailOTP.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EmailOTPModelImpl emailOTPModelImpl = this;

		emailOTPModelImpl._originalUserId = emailOTPModelImpl._userId;

		emailOTPModelImpl._setOriginalUserId = false;

		emailOTPModelImpl._setModifiedDate = false;

		emailOTPModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmailOTP> toCacheModel() {
		EmailOTPCacheModel emailOTPCacheModel = new EmailOTPCacheModel();

		emailOTPCacheModel.emailOTPId = getEmailOTPId();

		emailOTPCacheModel.companyId = getCompanyId();

		emailOTPCacheModel.userId = getUserId();

		emailOTPCacheModel.userName = getUserName();

		String userName = emailOTPCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			emailOTPCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			emailOTPCacheModel.createDate = createDate.getTime();
		}
		else {
			emailOTPCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			emailOTPCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			emailOTPCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.emailAddress = getEmailAddress();

		String emailAddress = emailOTPCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			emailOTPCacheModel.emailAddress = null;
		}

		Date lastSuccessDate = getLastSuccessDate();

		if (lastSuccessDate != null) {
			emailOTPCacheModel.lastSuccessDate = lastSuccessDate.getTime();
		}
		else {
			emailOTPCacheModel.lastSuccessDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.lastSuccessIP = getLastSuccessIP();

		String lastSuccessIP = emailOTPCacheModel.lastSuccessIP;

		if ((lastSuccessIP != null) && (lastSuccessIP.length() == 0)) {
			emailOTPCacheModel.lastSuccessIP = null;
		}

		Date lastFailDate = getLastFailDate();

		if (lastFailDate != null) {
			emailOTPCacheModel.lastFailDate = lastFailDate.getTime();
		}
		else {
			emailOTPCacheModel.lastFailDate = Long.MIN_VALUE;
		}

		emailOTPCacheModel.lastFailIP = getLastFailIP();

		String lastFailIP = emailOTPCacheModel.lastFailIP;

		if ((lastFailIP != null) && (lastFailIP.length() == 0)) {
			emailOTPCacheModel.lastFailIP = null;
		}

		emailOTPCacheModel.failedAttempts = getFailedAttempts();

		return emailOTPCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{emailOTPId=");
		sb.append(getEmailOTPId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", emailAddress=");
		sb.append(getEmailAddress());
		sb.append(", lastSuccessDate=");
		sb.append(getLastSuccessDate());
		sb.append(", lastSuccessIP=");
		sb.append(getLastSuccessIP());
		sb.append(", lastFailDate=");
		sb.append(getLastFailDate());
		sb.append(", lastFailIP=");
		sb.append(getLastFailIP());
		sb.append(", failedAttempts=");
		sb.append(getFailedAttempts());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.multi.factor.authentication.provider.email.otp.model.EmailOTP");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>emailOTPId</column-name><column-value><![CDATA[");
		sb.append(getEmailOTPId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailAddress</column-name><column-value><![CDATA[");
		sb.append(getEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastSuccessDate</column-name><column-value><![CDATA[");
		sb.append(getLastSuccessDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastSuccessIP</column-name><column-value><![CDATA[");
		sb.append(getLastSuccessIP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastFailDate</column-name><column-value><![CDATA[");
		sb.append(getLastFailDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastFailIP</column-name><column-value><![CDATA[");
		sb.append(getLastFailIP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>failedAttempts</column-name><column-value><![CDATA[");
		sb.append(getFailedAttempts());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EmailOTP.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EmailOTP.class, ModelWrapper.class
		};
	private long _emailOTPId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _emailAddress;
	private Date _lastSuccessDate;
	private String _lastSuccessIP;
	private Date _lastFailDate;
	private String _lastFailIP;
	private int _failedAttempts;
	private long _columnBitmask;
	private EmailOTP _escapedModel;
}