/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.otp.service.base;

import com.liferay.multi.factor.authentication.otp.model.HOTP;
import com.liferay.multi.factor.authentication.otp.service.HOTPService;
import com.liferay.multi.factor.authentication.otp.service.persistence.HOTPPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the hotp remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.multi.factor.authentication.otp.service.impl.HOTPServiceImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see com.liferay.multi.factor.authentication.otp.service.impl.HOTPServiceImpl
 * @see com.liferay.multi.factor.authentication.otp.service.HOTPServiceUtil
 * @generated
 */
public abstract class HOTPServiceBaseImpl extends BaseServiceImpl
	implements HOTPService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.multi.factor.authentication.otp.service.HOTPServiceUtil} to access the hotp remote service.
	 */

	/**
	 * Returns the hotp local service.
	 *
	 * @return the hotp local service
	 */
	public com.liferay.multi.factor.authentication.otp.service.HOTPLocalService getHOTPLocalService() {
		return hotpLocalService;
	}

	/**
	 * Sets the hotp local service.
	 *
	 * @param hotpLocalService the hotp local service
	 */
	public void setHOTPLocalService(
		com.liferay.multi.factor.authentication.otp.service.HOTPLocalService hotpLocalService) {
		this.hotpLocalService = hotpLocalService;
	}

	/**
	 * Returns the hotp remote service.
	 *
	 * @return the hotp remote service
	 */
	public HOTPService getHOTPService() {
		return hotpService;
	}

	/**
	 * Sets the hotp remote service.
	 *
	 * @param hotpService the hotp remote service
	 */
	public void setHOTPService(HOTPService hotpService) {
		this.hotpService = hotpService;
	}

	/**
	 * Returns the hotp persistence.
	 *
	 * @return the hotp persistence
	 */
	public HOTPPersistence getHOTPPersistence() {
		return hotpPersistence;
	}

	/**
	 * Sets the hotp persistence.
	 *
	 * @param hotpPersistence the hotp persistence
	 */
	public void setHOTPPersistence(HOTPPersistence hotpPersistence) {
		this.hotpPersistence = hotpPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HOTPService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HOTP.class;
	}

	protected String getModelClassName() {
		return HOTP.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = hotpPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.multi.factor.authentication.otp.service.HOTPLocalService.class)
	protected com.liferay.multi.factor.authentication.otp.service.HOTPLocalService hotpLocalService;
	@BeanReference(type = HOTPService.class)
	protected HOTPService hotpService;
	@BeanReference(type = HOTPPersistence.class)
	protected HOTPPersistence hotpPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
}