/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bemis.portal.twofa.device.manager.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Device service. Represents a row in the &quot;Bemis_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bemis.portal.twofa.device.manager.model.impl.DeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bemis.portal.twofa.device.manager.model.impl.DeviceImpl}.
 * </p>
 *
 * @author Prathima Shreenath
 * @see Device
 * @see com.bemis.portal.twofa.device.manager.model.impl.DeviceImpl
 * @see com.bemis.portal.twofa.device.manager.model.impl.DeviceModelImpl
 * @generated
 */
@ProviderType
public interface DeviceModel extends BaseModel<Device>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device model instance should use the {@link Device} interface instead.
	 */

	/**
	 * Returns the primary key of this device.
	 *
	 * @return the primary key of this device
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this device.
	 *
	 * @param primaryKey the primary key of this device
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the device ID of this device.
	 *
	 * @return the device ID of this device
	 */
	public long getDeviceId();

	/**
	 * Sets the device ID of this device.
	 *
	 * @param deviceId the device ID of this device
	 */
	public void setDeviceId(long deviceId);

	/**
	 * Returns the group ID of this device.
	 *
	 * @return the group ID of this device
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this device.
	 *
	 * @param groupId the group ID of this device
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this device.
	 *
	 * @return the company ID of this device
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this device.
	 *
	 * @param companyId the company ID of this device
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this device.
	 *
	 * @return the user ID of this device
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this device.
	 *
	 * @param userId the user ID of this device
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this device.
	 *
	 * @return the user uuid of this device
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this device.
	 *
	 * @param userUuid the user uuid of this device
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this device.
	 *
	 * @return the user name of this device
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this device.
	 *
	 * @param userName the user name of this device
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this device.
	 *
	 * @return the create date of this device
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this device.
	 *
	 * @param createDate the create date of this device
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this device.
	 *
	 * @return the modified date of this device
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this device.
	 *
	 * @param modifiedDate the modified date of this device
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the portal user ID of this device.
	 *
	 * @return the portal user ID of this device
	 */
	public long getPortalUserId();

	/**
	 * Sets the portal user ID of this device.
	 *
	 * @param portalUserId the portal user ID of this device
	 */
	public void setPortalUserId(long portalUserId);

	/**
	 * Returns the portal user uuid of this device.
	 *
	 * @return the portal user uuid of this device
	 */
	public String getPortalUserUuid();

	/**
	 * Sets the portal user uuid of this device.
	 *
	 * @param portalUserUuid the portal user uuid of this device
	 */
	public void setPortalUserUuid(String portalUserUuid);

	/**
	 * Returns the portal user name of this device.
	 *
	 * @return the portal user name of this device
	 */
	@AutoEscape
	public String getPortalUserName();

	/**
	 * Sets the portal user name of this device.
	 *
	 * @param portalUserName the portal user name of this device
	 */
	public void setPortalUserName(String portalUserName);

	/**
	 * Returns the email address of this device.
	 *
	 * @return the email address of this device
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this device.
	 *
	 * @param emailAddress the email address of this device
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the device i p of this device.
	 *
	 * @return the device i p of this device
	 */
	@AutoEscape
	public String getDeviceIP();

	/**
	 * Sets the device i p of this device.
	 *
	 * @param deviceIP the device i p of this device
	 */
	public void setDeviceIP(String deviceIP);

	/**
	 * Returns the browser name of this device.
	 *
	 * @return the browser name of this device
	 */
	@AutoEscape
	public String getBrowserName();

	/**
	 * Sets the browser name of this device.
	 *
	 * @param browserName the browser name of this device
	 */
	public void setBrowserName(String browserName);

	/**
	 * Returns the os name of this device.
	 *
	 * @return the os name of this device
	 */
	@AutoEscape
	public String getOsName();

	/**
	 * Sets the os name of this device.
	 *
	 * @param osName the os name of this device
	 */
	public void setOsName(String osName);

	/**
	 * Returns the verified of this device.
	 *
	 * @return the verified of this device
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this device is verified.
	 *
	 * @return <code>true</code> if this device is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this device is verified.
	 *
	 * @param verified the verified of this device
	 */
	public void setVerified(boolean verified);

	/**
	 * Returns the temp device of this device.
	 *
	 * @return the temp device of this device
	 */
	public boolean getTempDevice();

	/**
	 * Returns <code>true</code> if this device is temp device.
	 *
	 * @return <code>true</code> if this device is temp device; <code>false</code> otherwise
	 */
	public boolean isTempDevice();

	/**
	 * Sets whether this device is temp device.
	 *
	 * @param tempDevice the temp device of this device
	 */
	public void setTempDevice(boolean tempDevice);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Device device);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Device> toCacheModel();

	@Override
	public Device toEscapedModel();

	@Override
	public Device toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}